-- migrations/9000_planner_init.sql: fork-owned, hand-written. Never edit once applied (add 9001_planner_...).
--
-- The planning cockpit tables (docs/planning-cockpit-implementation-plan.md, section 3).
-- Not generated by drizzle-kit and not listed in migrations/meta/_journal.json:
-- never run pnpm db:generate for these tables (G3, the fork exception to AGENTS.md).
-- Wrangler orders migration files by leading number, so this one is applied after
-- 0033 and still lets later upstream 00NN files apply after it. Vitest suites apply it
-- with applyPlannerMigrations (packages/db/src/planner-migrations.ts).
--
-- Rules for this file and every 9NNN_planner_ file after it:
--   G10  no foreign key to an upstream table (planner-internal keys are fine)
--   G11  no triggers
--   G12  never edit a file once it is applied to a real database (dev or live)
--   G13  additive only: never rebuild a planner table here
CREATE TABLE `planner_task_plan` (
  `task_id` text PRIMARY KEY NOT NULL,             -- upstream tasks.id, no FK (G10)
  `user_id` text NOT NULL,
  `horizon` text,                                  -- day | week | month | NULL (backlog)
  `period_start` text,                             -- YYYY-MM-DD; NULL iff horizon is NULL
  `carry_count` integer NOT NULL DEFAULT 0,
  `dropped_at` text,
  `created_at` text NOT NULL,
  `updated_at` text NOT NULL
);
--> statement-breakpoint
CREATE INDEX `planner_task_plan_user_period_idx` ON `planner_task_plan` (`user_id`,`horizon`,`period_start`);
--> statement-breakpoint
CREATE TABLE `planner_task_event` (
  `id` integer PRIMARY KEY AUTOINCREMENT NOT NULL, -- tie-breaker only
  `user_id` text NOT NULL,
  `task_id` text NOT NULL,                         -- no FK: history outlives the task
  `task_title` text,                               -- snapshot at copy time
  `type` text NOT NULL,                            -- see "Event types"
  `data` text NOT NULL DEFAULT '{}',               -- JSON
  `source` text NOT NULL,                          -- 'activity' | 'sync' | 'planner'
  `source_ref` text,                               -- idempotency key for activity/sync events
  `actor_type` text,                               -- user | agent | NULL
  `actor_name` text,
  `occurred_at` text NOT NULL,                     -- when it happened (source timestamp)
  `created_at` text NOT NULL                       -- when it was archived
);
--> statement-breakpoint
CREATE UNIQUE INDEX `planner_task_event_source_ref_uq` ON `planner_task_event` (`source`,`source_ref`) WHERE `source_ref` IS NOT NULL;
--> statement-breakpoint
CREATE INDEX `planner_task_event_task_idx` ON `planner_task_event` (`task_id`,`occurred_at`);
--> statement-breakpoint
CREATE INDEX `planner_task_event_user_idx` ON `planner_task_event` (`user_id`,`occurred_at`);
--> statement-breakpoint
CREATE TABLE `planner_task_seen` (                 -- snapshot used to detect delete/restore/purge
  `task_id` text PRIMARY KEY NOT NULL,
  `user_id` text NOT NULL,
  `title` text NOT NULL,
  `status` text NOT NULL,
  `project_id` text,
  `deleted_at` text,
  `last_seen_at` text NOT NULL
);
--> statement-breakpoint
CREATE INDEX `planner_task_seen_user_idx` ON `planner_task_seen` (`user_id`);
--> statement-breakpoint
CREATE TABLE `planner_sync_state` (
  `user_id` text PRIMARY KEY NOT NULL,
  `activity_watermark` text,                       -- max task_activity.created_at copied
  `activity_last_id` integer,                      -- max task_activity.id seen (may drop after an upstream rebuild)
  `last_sync_at` text,
  `status` text NOT NULL DEFAULT 'ok',             -- ok | paused
  `paused_reason` text
);
--> statement-breakpoint
CREATE TABLE `planner_project_node` (              -- goal tree over upstream projects
  `project_id` text PRIMARY KEY NOT NULL,          -- upstream projects.id, no FK (G10)
  `user_id` text NOT NULL,
  `parent_project_id` text REFERENCES `planner_project_node`(`project_id`) ON DELETE SET NULL,
  `level` text,                                    -- validated slug (D3) or NULL
  `period_start` text,
  `period_end` text,
  `sort_order` integer NOT NULL DEFAULT 0,
  `created_at` text NOT NULL,
  `updated_at` text NOT NULL
);
--> statement-breakpoint
CREATE INDEX `planner_project_node_user_parent_idx` ON `planner_project_node` (`user_id`,`parent_project_id`,`sort_order`);
